### ISSUE TITLE
[Feature Request] Make TypeChat platform agnostic (Remove Node.js dependencies)

### ISSUE THREAD

**Issue by shiqimei** [microsoft/TypeChat#105]
Hi @steveluc ! Can we make typechat platform agnostic in the near future? Remove node.js built-in dependencies like `fs` module to make it run in the **edge runtime** or **web browser** without any concern.

We can provide a higher level abstract layer or an adapter to let users provide `fs` implementation or `readFile` implementaiton to avoid dependency maybe?

**Comment by shiqimei** [comment]
I think it's duplicate of #102

**Comment by xumx** [comment]
I have a version of it working with Deno.

Example
`import { createJsonTranslator } from "https://esm.sh/gh/keyreply/typechat@0.0.10/src/index.ts";`

The NodeJS interactive mode is disabled. (not required for worker usage)

**Comment by shiqimei** [comment]
> 

Thanks @xumx for pointing this out!
