### ISSUE TITLE
Does repair actually work?

### ISSUE THREAD

**Issue by ChristianWeyer** [microsoft/TypeChat#122]
Hi :-)

we are not actually sending over a revised JSON program object here:
https://github.com/microsoft/TypeChat/blob/ec3a37c44168ff5d3fef954a62278e205a3bab4f/src/program.ts#L215

Is this an oversight?

Thank you.

**Comment by olivier-martin-sf** [comment]
I am not part of the TypeChat team, however my guess is that this sentence is an invite for guiding the LLM to produce the revised JSON program object based on the validationError. The revised JSON program object is going to be the response of the model

**Comment by caridy** [comment]
That's correct @olivier-martin-sf. The intent is to get the LLM to complete the text by producing the revised JSON program as the output of the LLM.

**Comment by ChristianWeyer** [comment]
Thank you!
