### ISSUE TITLE
Cannot find module 'readline/promises' error in production

### ISSUE THREAD

**Issue by vyktoremario** [microsoft/TypeChat#131]
I was using Typechat in a project I worked on and it worked fine during development, The deployed version was raising the following error from that library: `Cannot find module 'readline/promises'`,

Could it be that it's not bundled properly, or doesn't work in a lambda environment for some reason?

I need some help here.

**Comment by SweetpopcornSimon** [comment]
Hey! 

What version of node are you using?

**Comment by vyktoremario** [comment]
Hi @SweetpopcornSimon I am using version ^18.13.0 of node

**Comment by SweetpopcornSimon** [comment]
Okay I had that problem and the issue was I didn't have the right node or typescript version, I upgraded node to 18.17.1 and my package.json looks like this 
` "devDependencies": {
    "@types/node": "^20.3.1",
    "copyfiles": "^2.4.1",
    "typescript": "^5.1.3"
  }`

This thread helped me find the issue https://github.com/TypeStrong/ts-node/discussions/1638

**Comment by vyktoremario** [comment]
@SweetpopcornSimon thanks for the response.
I will try this out and let you know if it works

**Comment by SweetpopcornSimon** [comment]
@vyktoremario did it work?

**Comment by vyktoremario** [comment]
@SweetpopcornSimon It did not work.
We had to disable it for now as it was blocking some features from going live.

**Comment by DanielRosenwasser** [comment]
It sounds like this was an issue with the target runtime. I believe if you use Node 20 or later, you should have no issues here.

**Comment by Himanshi3047** [comment]
I am also facing this issue , My node version is also v20
