### ISSUE TITLE
How to log the prompt generated by typechat?

### ISSUE THREAD

**Issue by superwangnan** [microsoft/TypeChat#181]
Hi team,
Thanks for great job at first :).
I am a newbie for Typechat. As I understand, typechat will generate prompt based on customer query and response schema. So, I want to know if we have any setting to make typechat log or show the prompt generated?
Thanks

**Comment by olawalejuwonm** [comment]
You can play with the source code to do that.

I've done that in the past, it's more of prompt engineering instructing the
model to act as service that generate response based on the interface.

In your node module, check the folder for typechat, review the code and
console createTranslator (or similar variable name)

**Comment by superwangnan** [comment]
Got it! Thanks
