### ISSUE TITLE
when will v0.1.0 be released to npm?

### ISSUE THREAD

**Issue by Alexixyc** [microsoft/TypeChat#187]
Hi~Thanks to this library,  it helps me a lot during my current work.

I found that the master branch version is 0.1.0, and the api is different to its  npm latest version(0.0.10), when will v0.1.0 be released ?

**Comment by Githamza** [comment]
Waiting also , becuse when using link npm then npm build the package is not included in the dist forlder, I hade to copy it every time

**Comment by claus-topholt-private** [comment]
Also waiting here - any timeline?

**Comment by Githamza** [comment]
Any updates ?

**Comment by DanielRosenwasser** [comment]
Hey all, we just shipped TypeChat 0.1.0 to npm! My apologies about the delay, but thank you all for your patience.

You can read more here: https://microsoft.github.io/TypeChat/blog/announcing-typechat-0-1-0/

**Comment by Githamza** [comment]
@DanielRosenwasser  see my last issue , have you an idea ?


https://github.com/microsoft/TypeChat/issues/227
