### ISSUE TITLE
typechat 0.1.0 not found 

### ISSUE THREAD

**Issue by Githamza** [microsoft/TypeChat#227]
After installing new 0.1.0 typechat version I'm getting this error 

1 import { createLanguageModel, createJsonTranslator, Success } from "typechat";

==> Cannot find module 'typechat' or its corresponding type declarations.ts(2307)

I have it inside node_modules :

![image](https://github.com/microsoft/TypeChat/assets/11578288/006fffbd-4ffd-4a5d-a119-83c2d7c4b137)

I think there is not an index.d.ts file

**Comment by DanielRosenwasser** [comment]
Is it possible that you are using `"module": "commonjs"`? If so, you'll need to switch to `"module": "node16"` or later.
