### ISSUE TITLE
@azure/openai vs axios

### ISSUE THREAD

**Issue by deyaaeldeen** [microsoft/TypeChat#32]
Did you consider using [`@azure/openai`](https://www.npmjs.com/package/@azure/openai)? If yes, we would love to hear what were the pain points and whether there is any feedback 😊

If not, please checkout the following samples of using completions:
- [openai.com](https://github.com/Azure/azure-sdk-for-js/blob/main/sdk/openai/openai/samples/v1-beta/typescript/src/openAi.ts)
- [Azure OpenAI](https://github.com/Azure/azure-sdk-for-js/blob/main/sdk/openai/openai/samples/v1-beta/typescript/src/completions.ts)

As you notice, the library works with both openai.com and Azure OpenAI and provides a seamless experience of switching between either.

**Comment by ahejlsberg** [comment]
> Did you consider using [@azure/openai](https://www.npmjs.com/package/@azure/openai)?

We did, but we wanted to reduce our dependencies to a minimum and have an implementation that is easily adapted to _any_ LLM (OpenAI or not). TBH, we need very little but a basic REST endpoint with some retry logic.

**Comment by ahejlsberg** [comment]
I should add that all LLM interaction is handled through a simple [TypeChatLanguageModel](https://github.com/microsoft/TypeChat/blob/main/src/model.ts#L10C1-L10C41) interface. It's very easy to substitute your own implementation for whichever LLM API you prefer.
