### ISSUE TITLE
Does this library consume a lot of the openai API?

### ISSUE THREAD

**Issue by luo-li-ba-suo** [microsoft/TypeChat#33]
Does this library consume a lot of the openai API?

Does it change the LLM decoding process or repeat the openai API call for each blank in the json format as Guidance?

**Comment by DanielRosenwasser** [comment]
I'm not entirely familiar with those approaches - I don't believe this library does anything of the sort. TypeChat is mostly model-agnostic and just needs a completion function. If you provide a [`TypeChatLanguageModel`](https://github.com/microsoft/TypeChat/blob/db26f4ea0e0feb44b67d79db3e95c91b82531b41/src/model.ts#L10-L24), then TypeChat just works with that model.

https://github.com/microsoft/TypeChat/blob/db26f4ea0e0feb44b67d79db3e95c91b82531b41/src/model.ts#L10-L24

As you can see, all you really need is to provide a function with the signature `(prompt: string) => Promise<Result<string>>`.
