### ISSUE TITLE
"Restaurant" example has wrong output in README

### ISSUE THREAD

**Issue by Marcono1234** [microsoft/TypeChat#62]
The "Restaurant" example has a wrong output in the "Usage" section of the README[^1], if I understand the input correctly, it should be:
```diff
-2 large pizza with mushrooms
+1 large pizza with mushrooms
+1 large pizza with sausage
 1 small pizza with sausage
 1 whole Greek salad
 1 Pale Ale
 1 Mack and Jacks
```

If this is intentional, then maybe there should be a sentence below it explaining this to avoid confusion, for example:
> This shows that TypeChat may not be 100% accurate, and you may want to consider asking the user for confirmation before performing any action. The output here erroneously shows 2 mushroom pizzas and 1 sausage pizza, while it should be 1 mushroom pizza and 2 sausage pizzas (one large and one small).

[^1]: And the "Input" might be incorrect as well, shouldn't it be only `🍕>` instead of `😀> 🍕>`?

**Comment by DanielRosenwasser** [comment]
@steveluc double-checking to see if this was intentional.

**Comment by steveluc** [comment]
Looks like just a typo

**Comment by DanielRosenwasser** [comment]
Open to PRs if you want to fix it before us. 😄

**Comment by isurumaldeniya** [comment]
can I fix this ? @DanielRosenwasser

**Comment by weykon** [comment]
the text: `I want three pizzas, one with mushrooms and the other two with sausage.  Make one sausage a small.  And give me a whole Greek and a Pale Ale.  And give me a Mack and Jacks.`

I ran 5 times, it all output: 

```
    1 large pizza with mushrooms
    2 large pizza with sausage
    1 small pizza with sausage
    1 whole Greek salad
    1 Pale Ale
    1 Mack and Jacks
```
> This shows that TypeChat may not be 100% accurate, and you may want to consider asking the user for confirmation before performing any action. The output here erroneously shows 2 mushroom pizzas and 1 sausage pizza, while it should be 1 mushroom pizza and 2 sausage pizzas (one large and one small).

I think adding this is needed

**Comment by steveluc** [comment]
:-) thanks for the diligence on this.  From site/src/docs/examples.md (emphasis added):

| Name | Description |
| ---- | ----------- |
| [Restaurant](https://github.com/microsoft/TypeChat/tree/main/examples/restaurant) | An intelligent agent for taking orders at a restaurant. Similar to the coffee shop example, but uses a more complex schema to model more complex linguistic input. The prose files *illustrate the line between simpler and more advanced language models in handling compound sentences, distractions, and corrections*. This example also shows how we can use TypeScript to provide a user intent summary. |

**Comment by steveluc** [comment]
I think it's pretty amazing that GPT-4 gets examples like this.  I agree 100% that we should be clear that not all models will get the examples and also that there is always at least one model that does get the correct output.  To work toward that I checked in #67.

**Comment by steveluc** [comment]
Will leave this open to hear from anyone who wants to suggest further elaboration or clarification.

**Comment by weykon** [comment]
oh! I understand. On this doc issue, I think it is possible to maintain a wrong output. I will explain it below the output. Then I will compare the models of different intelligences and improve the document under this comparison.

**Comment by weykon** [comment]
> I think it's pretty amazing that GPT-4 gets examples like this. I agree 100% that we should be clear that not all models will get the examples and also that there is always at least one model that does get the correct output. To work toward that I checked in #67.

Okay, I would like to ask, so in the Restaurant document, shall I add this interesting comparison of the output of different models, so as to achieve future reference for experiments?

**Comment by DanielRosenwasser** [comment]
I also added a few edits to #66 which I think can give some more context. I think that's good to go.
