### ISSUE TITLE
Support to add prompts to the system prompt.

### ISSUE THREAD

**Issue by dohooo** [microsoft/TypeChat#76]
```
    function createRequestPrompt(request: string) {
        return `${prefixPrompt}\nYou are a service that translates user requests into JSON objects of type "${validator.typeName}" according to the following TypeScript definitions:\n` +
            `\`\`\`\n${validator.schema}\`\`\`\n` +
            `The following is a user request:\n` +
            `"""\n${request}\n"""\n` +
            `The following is the user request translated into a JSON object with 2 spaces of indentation and no properties with the value undefined:\n`;
    }
```

Is it possible to support adding prefix prompt? As this approach, we can define more customized prompt on the global level.
e.g. 

const prefixPrompt = "You need to make inferences about what the user hasn't mentioned, based on what has been provided."

**Comment by ahejlsberg** [comment]
This is pretty easy to do. Just assign a new function to `createRequestPrompt` after you call `createJsonTranslator`. For example:

```ts
const translator = createJsonTranslator<Cart>(model, schema, "Cart");
const defaultRequestPrompt = translator.createRequestPrompt;
translator.createRequestPrompt = request => `${prefixPrompt}\n${defaultRequestPrompt(request)}`;
```

**Comment by dohooo** [comment]
@ahejlsberg Thanks a lot!

**Comment by AndyBoat** [comment]
Maybe it's better to add this issue to FAQ ? I think this is quite helpful for different concrete purpose, which are not described clearly  by typescript types.
