### ISSUE TITLE
all samples package.json do not have typechat as a dependency

### ISSUE THREAD

**Issue by cicorias** [microsoft/TypeChat#81]
Not sure if this is intentional or not but the `package.json` in each of the samples is missing the dependency for typechat. 

i.e. [https://github.com/microsoft/TypeChat/blob/main/examples/calendar/package.json](https://github.com/microsoft/TypeChat/blob/main/examples/calendar/package.json)

**Comment by DanielRosenwasser** [comment]
@JakeBailey has a branch that fixes this and introduces pnpm so this problem *shouldn't* happen again.
